<div class="empdetails">
    <div class="sidebodyhead">
        <h4 class="m-0">Company Details</h4>
    </div>
    <div class="cards mt-3">
        <div class="cmpdetails mb-3">
            <div class="maincard row">
                <a class="editicon" href="./edit_cmp_details.php?com=<?php echo $com_id; ?>" data-bs-toggle="tooltip"
                    data-bs-title="Edit Company Details">
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>
                <?php
                // $cmp_st = $fetch->table_list_id('m_cmp2', 'f_id', $com_id);
                // $store = json_decode($cmp_st['store']);
                $cmp_st = $fetch->table_list_id('m_cmp2', 'f_id', $com_id);
                $store = [];
                $b_acc = [];

                if (!empty($cmp_st)) {
                    $store = json_decode($cmp_st['store'], true) ?? [];
                    $b_acc = json_decode($cmp_st['b_acc'], true) ?? [];
                }

                $lastItem = end($store);

                $b_acc = json_decode($cmp_st['b_acc']);
                $b_last = end($b_acc);

                ?>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Store Accounts</h6>
                    <h5 class="mb-0"><?php
                    foreach ($store as $st) {

                        if ($st === $lastItem) {
                            echo $st;  // Print the last element without a comma
                        } else {
                            echo $st . ', ';  // Print with a comma for others
                        }
                    }
                    ?>
                    </h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Business Account</h6>
                    <h5 class="mb-0"><?php
                    foreach ($b_acc as $bt) {

                        if ($bt === $b_last) {
                            echo $bt;  // Print the last element without a comma
                        } else {
                            echo $bt . ', ';  // Print with a comma for others
                        }
                    }
                    ?></h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Currently Using Software</h6>
                    <h5 class="mb-0"><?php echo $cmp_st['soft']; ?></h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Software Name</h6>
                    <h5 class="mb-0"><?php echo $cmp_st['soft_name']; ?></h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Turnover</h6>
                    <h5 class="mb-0"><?php echo $cmp_st['turn_over']; ?></h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">No. Of Employee</h6>
                    <h5 class="mb-0"><?php echo $cmp_st['emp_no']; ?></h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Customer Rating</h6>
                    <h5 class="mb-0"><?php echo $cmp_st['cus_rate']; ?></h5>
                </div>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Remarks</h6>
                    <h5 class="mb-0"><?php echo $cmp_st['remarks']; ?></h5>
                </div>
                <?php
                // $emp_det = $fetch->table_list_id('m_emp', 'id', $cmp_st['mgt_emp'])
                $emp_det = null;

                if (!empty($cmp_st) && !empty($cmp_st['mgt_emp'])) {
                    $emp_det = $fetch->table_list_id('m_emp', 'id', $cmp_st['mgt_emp']);
                }
                ?>
                <div class="col-sm-12 col-md-3 col-xl-3 mb-3">
                    <h6 class="mb-1">Leads Generated By</h6>
                    <h5 class="mb-0">
                        <?php echo $emp_det['name'] ?? 'N/A'; ?>
                    </h5>

                </div>
            </div>
        </div>

        <div class="bankdetails mb-3">
            <div class="maincard row">
                <a class="editicon" href="./add_cmp_contact_person.php?com=<?php echo $com_id; ?>"
                    data-bs-toggle="tooltip" data-bs-title="Add Contact Person">
                    <i class="fa-solid fa-user-plus"></i>
                </a>
                <?php
                $cmp_cn = $fetch->table_list_arr('m_cmp3', 'f_id', $com_id);

                ?>
                <table class="table mt-3">
                    <thead>
                        <tr>
                            <th>Contact Person Name</th>
                            <th>Contact Person Role</th>
                            <th>Contact Person Number</th>
                            <th>Contact Person Email</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php
                        foreach ($cmp_cn as $cmp_con) {
                            ?>
                            <tr>
                                <td><?php echo $cmp_con['con_name']; ?></td>
                                <td><?php echo $cmp_con['con_role']; ?></td>
                                <td><?php echo $cmp_con['con_num']; ?></td>
                                <td><?php echo $cmp_con['con_email']; ?></td>
                                <td>
                                    <div class="d-flex gap-2">
                                        <a href="./edit_cmp_contact_person.php?com_prime=<?php echo $cmp_con['id']; ?>"
                                            data-bs-toggle="tooltip" data-bs-title="Edit Contact Person"><i
                                                class="fa-solid fa-pen-to-square"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>